version: '3.8'

services:
  audio-to-sheet:
    build: .
    container_name: audio-to-sheet-nvidia
    ports:
      - "5000:5000"
    volumes:
      - .:/app # Permet le rechargement à chaud (Hot-Reload) si vous modifiez le code source
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - FLASK_ENV=development
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
